### ISSUE TITLE
1time buy success and stop.

### ISSUE THREAD

**Issue by nextnaro** [binary-com/deriv-api#16] opened 2020-01-25 17:39 UTC
https://github.com/binary-com/deriv-api/blob/master/examples/a_simple_bot.js

**get account balance is working can repeat many time in loop.**
async function main() {
    while (1)  {
        const account = await api.account(token);
        const { balance } = account;
        console.log(`Your current balance is: ${balance.currency} ${balance.display}`);
   }
}
**Out put**
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40
Your current balance is: USD 13,464.40

**after add by contract only buy 1 time and stop.**
async function main() {
    while (1)  {
        const account = await api.account(token);

        const { balance } = account;

        console.log(`Your current balance is: ${balance.currency} ${balance.display}`);
        const contract = await api.contract({
            contract_type: 'CALL',
            currency: balance.currency,
            amount: 10,
            duration: 5,
            duration_unit: 't',
            symbol: 'R_10',
            basis: 'stake',
        });
        const buy = await contract.buy();
      
   }
}
**out put only buy 1 time  and stop**
Your current balance is: USD 13,473.93
**buy and loss**
Your current balance is: USD 13,463.93

what im did wrong? all follow example script

**Comment by isaacdalmarco** [comment] 2020-08-18 13:28
Hello, did you get to solve this?

**Comment by nextnaro** [comment] 2020-08-18 13:44
nope.
I'm not a major programmer.

**Comment by salar-fs** [comment] 2020-10-18 07:09
Hey guysI I can't understand what you mean. Could you elaborate a bit more?

**Comment by victorfds** [comment] 2020-10-18 19:25
@salar-fs , the problem is the incapability of buy repeated times in a row with only one execution.
If there is a way it is not shared in docs.

**Comment by salar-fs** [comment] 2020-10-19 07:29
I think the reason is you skip the call to forget current proposal subscription:
`api.basic.forgetAll('proposal');`
Sure you wont find these tips in the docs but we're trying to add various bot samples soon.

**Comment by victorfds** [comment] 2020-10-19 13:36
Thank you, @salar-fs . I'll try it.

**Comment by victorfds** [comment] 2020-10-19 13:57
@salar-fs , Everything went well. The problem was the missing functions: ```api.basic.forget()``` and ```api.basic.forgetAll()``` after contract sold, now it has been resolved.

**Comment by salar-fs** [comment] 2020-10-19 13:59
Nice! So we'll close this and #37 as well.

**Closed** 2020-10-20 02:00 UTC
